#!/usr/bin/env python3
import sys, curses

screen = curses.initscr()
curses.start_color()
curses.curs_set(0)
curses.noecho()
curses.use_default_colors()
for i in range(0, curses.COLORS):
        curses.init_pair(i + 1, i, -1)

def run(self):
	while True:
		try:
			c = screen.getch()
		except:
			sys.exit(0)

		old = c
		c = curses.keyname(c)
		screen.clear()

		screen.addstr(0, 0, c)
		screen.addstr(1, 0, str(len(c)))
		screen.addstr(2, 0, str(old))

		screen.refresh()

curses.wrapper(run)
