#!/usr/bin/python3
import curses
import importlib
venicGlobals = {}
venicGlobals["curses"] = curses
venicGlobals["importlib"] = importlib

debug = False

# some way of loading the modules and orders as last stored
#	- load files
#		- python code in standardized functions ("hooks")
#			- .start()
#				- maybe accept arguments?
#				- creates definitions, calls, variables, etc
#			- .keybindings?
#				- no, keybindings would be a folder in modules that would have different python files with names like C-o that contain references to methods that would be loaded at .start
#			- .loop()
#				- the code that would be run on one frame/input tick

#main code base gets modules, probably based on unified `modules` file, figures out how what to import
#makes operational stack
#runs `start` stack
#loads keybindings, creates interpreter for keypresses inputted
#runs, as a loop (haha), `loop` stack
	# would keybindings be a module of its own? I wouldn't think so...
		# possible advantage would be try except handling of ctrl-C code... think about it for a bit
		# yeah, go with a module of its own...

moduleListFile = open("./config/modules")
moduleNameList = [line.rstrip('\n') for line in moduleListFile]
moduleListFile.close()

startModuleFile = open("./config/start")
startModuleNames = [line.rstrip('\n') for line in startModuleFile]
startModuleFile.close()

loopModuleFile = open("./config/loop")
loopModuleNames = [line.rstrip('\n') for line in loopModuleFile]
loopModuleFile.close()

modules = {}

for module in moduleNameList:
	modules[module] = importlib.import_module("modules."+module)

venicGlobals["modules"] = modules

for module in startModuleNames:
	modules[module].start(venicGlobals)


#debug = True
while True:
	if debug == False:
		try:
			for module in loopModuleNames:
				modules[module].loop(venicGlobals)
		except:
			startModuleNames.reverse()
			for module in startModuleNames:
				modules[module].kill(venicGlobals)
			break
	elif debug == True:
		for module in loopModuleNames:
				modules[module].loop(venicGlobals)

#print([i for i in venicGlobals])
