#!/usr/bin/env python3
import traceback, sys
"""
import cProfile
from pstats import Stats
prof = cProfile.Profile()
prof.enable()
"""

from modules.engine import Engine
engine = Engine()

while True:
	try:
		engine.turn()
	except KeyboardInterrupt:
		engine.terminate()
		break
	except:
		engine.terminate()
#		prof.print_stats(sort="cumulative")
		str(traceback.print_exc())  # Print the exception
		break

# prof.print_stats(sort="cumulative")
sys.exit(0)
