#!/usr/bin/python3
### statistics on programs
import cProfile
from pstats import Stats
prof = cProfile.Profile()
prof.enable()
### legacy from venic
# import curses
# import importlib
import traceback
# import pygments
# import pygments.lexers as lexers
# import os
###
from modules.engine import Engine
scheduler = Engine()
while True:
	try:
		scheduler.turn()
	except:
		scheduler.terminate()
		str(traceback.print_exc())  # Print the exception
		break
#root_dir = os.path.dirname(os.path.realpath(__file__))
#prof.print_stats(sort="cumulative")
